site_name: 'Django Bootstrap Customizer'
site_url: 'https://johnfraney.github.io/django-bootstrap-customizer/'
repo_name: 'johnfraney/django-bootstrap-customizer'
repo_url: 'https://github.com/johnfraney/django-bootstrap-customizer'

nav:
  - Home: index.md
  - Models: models.md
  - Template Tags: template_tags.md
  - Views: views.md
  - Middleware: middleware.md
  - Advanced Usage: advanced_usage.md
  - Example Project: example_project.md
  - FAQ: faq.md
dev_addr: '127.0.0.1:8008'

# Copyright
copyright: 'Copyright &copy; 2018 John Franey'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/johnfraney'

# Theme configuration
theme:
  name: 'material'
  logo:
    icon: 'palette'
  palette:
    primary: 'deep purple'
    accent: 'indigo'

# Google Analytics
google_analytics:
  - 'UA-125394319-2'
  - 'auto'

# Extensions
markdown_extensions:
  - codehilite
